<a href="https://colab.research.google.com/github/dom-rivera/People-Analytics/blob/main/People_Analytics_Attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## People Analytics Refresher 27 October 2026

1. Load and inspect: get to know the data.

2. Clean and prepare: fix types, drop useless columns, create new fields.

3. Descriptive analytics: attrition rates by segment, the “what happened”.

4. Visualization: charts an HR leader can read in 5 seconds.

5. Statistical testing: is a difference real or noise?

6. Explanatory modeling: logistic regression, the “why”.

7. Predictive modeling: who is at risk, and how much to trust the model.

8. Business story: cost, recommendations, a one-page memo.

# 1. Load and Inspect Data

In [1]:
# Load and Inspect Data
import pandas as pd

df = pd.read_csv("ibm_hr_attrition.csv")
print(df.shape)
df.head()

(1470, 35)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [3]:
df.isna().sum().sum()

np.int64(0)

In [4]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [5]:
df["Education"].value_counts().sort_index()
df["PerformanceRating"].value_counts().sort_index()

PerformanceRating
3    1244
4     226
Name: count, dtype: int64

In [6]:
df.describe(include="object")

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
count,1470,1470,1470,1470,1470,1470,1470,1470,1470
unique,2,3,3,6,2,9,3,1,2
top,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Y,No
freq,1233,1043,961,606,882,326,673,1470,1054

In [7]:
print(df["Attrition"].value_counts())
print(df["Attrition"].value_counts(normalize=True))

Attrition
No     1233
Yes     237
Name: count, dtype: int64
Attrition
No     0.838776
Yes    0.161224
Name: proportion, dtype: float64

In [8]:
import numpy as np
p = 237 / 1470
n = 1470
margin = 1.96 * np.sqrt(p * (1 - p) / n)
print(f"{p:.1%} ± {margin:.1%}  →  {p - margin:.1%} to {p + margin:.1%}")

16.1% ± 1.9%  →  14.2% to 18.0%

1. How many employees and how many columns are there? There are 1470 employees and 26 columns

2. Are there any missing values? How can you tell from info()? df. There are no missing values from the dataset. The info() shows each column’s data type and how many values are filled in. Missing data shows up as a count lower than the row count. Additionally, missing values can be found using df.isna().sum().sum()

3. What is the attrition rate? Is that high or low in your view? The attrition rate is 16.1%. The attrition rate of 16.1 is equivalent to 237 employees. It's above the typical turnover benchmarks (13% for US and 8 to 17% across Philippine industries).

Sources:

https://www.imercer.com/content/article/employee-turnover.aspx


https://malaya.com.ph/business/enterprise/9-in-10-firms-have-incentive-plans-wages-to-rise-5-5


4. In describe(), find three columns where every employee has the same value. Why are they useless for analysis? The three columns where employees have the same values are EmployeeCount, StandardHours, and Over18. They are useless for analysis because they do not offer differences and variations.

5. Look at JobSatisfaction, Education and PerformanceRating. They’re stored as numbers, but what are they really? (Hint: think about what a “3” on a survey means compared with a “3” in years of experience.). In data sometimes numbers do not have numerical value. This is what we called coding. A value of 3 on JobSatifaction can be high level label for it. An Education of 3 can be a form of education attainment level. And lastly, a PerformanceRating of 3 can be something similar to Excellent.

# 2. Clean and prepare

In [9]:
df_clean = df.copy()
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [10]:
df_clean = df_clean.set_index("EmployeeNumber")

constant_cols = ["EmployeeCount", "StandardHours", "Over18"]
df_clean = df_clean.drop(columns=constant_cols)

df_clean

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
EmployeeNumber,,,,,,,,,,,,,,,,,,,,,
1,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
2,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
4,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
5,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
7,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2061,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,3,3,1,17,3,3,5,2,0,3
2062,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,3,1,1,9,5,3,7,7,1,7
2064,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,4,2,1,6,0,3,6,2,0,3
2065,49,No,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,3,4,0,17,3,2,9,6,0,8
2068,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,3,1,0,6,3,4,4,3,1,2

In [11]:
df_clean["Left"] = (df_clean["Attrition"] == "Yes").astype(int)
df_clean[["Attrition", "Left"]].head()

               Attrition  Left
EmployeeNumber
1                    Yes     1
2                     No     0
4                    Yes     1
5                     No     0
7                     No     0

In [12]:
df_clean["Left"].mean()

np.float64(0.16122448979591836)

In [14]:
satisfaction_map = {1: "Low", 2: "Medium", 3: "High", 4: "Very High"}
education_map = {1: "Below College", 2: "College", 3: "Bachelor", 4: "Master", 5: "Doctor"}
worklife_map = {1: "Bad", 2: "Good", 3: "Better", 4: "Best"}
performance_map = {1: "Low", 2: "Good", 3: "Excellent", 4: "Outstanding"}
df_clean["JobSatisfaction_label"] = df_clean["JobSatisfaction"].map(satisfaction_map)
df_clean["Education_label"] = df_clean["Education"].map(education_map)
df_clean["WorkLifeBalance_label"] = df_clean["WorkLifeBalance"].map(worklife_map)
df_clean["PerformanceRating_label"] = df_clean["PerformanceRating"].map(performance_map)
df_clean[["JobSatisfaction", "JobSatisfaction_label"]].head()

                JobSatisfaction JobSatisfaction_label
EmployeeNumber
1                             4             Very High
2                             2                Medium
4                             3                  High
5                             3                  High
7                             2                Medium

In [15]:
sat_order = ["Low", "Medium", "High", "Very High"]
df_clean["JobSatisfaction_label"] = pd.Categorical(
    df_clean["JobSatisfaction_label"], categories=sat_order, ordered=True
)

df_clean["JobSatisfaction_label"].value_counts().sort_index()

JobSatisfaction_label
Low          289
Medium       280
High         442
Very High    459
Name: count, dtype: int64

In [16]:
df_clean["AgeGroup"] = pd.cut(
    df_clean["Age"],
    bins=[17, 25, 35, 45, 55, 60],
    labels=["18-25", "26-35", "36-45", "46-55", "56-60"]
)
df_clean["AgeGroup"].value_counts().sort_index()

AgeGroup
18-25    123
26-35    606
36-45    468
46-55    226
56-60     47
Name: count, dtype: int64

In [17]:
df_clean["TenureBand"] = pd.cut(
    df_clean["YearsAtCompany"],
    bins=[-1, 1, 3, 5, 10, 40],
    labels=["0-1 yrs", "2-3 yrs", "4-5 yrs", "6-10 yrs", "11+ yrs"]
)
df_clean["TenureBand"].value_counts().sort_index()

TenureBand
0-1 yrs     215
2-3 yrs     255
4-5 yrs     306
6-10 yrs    448
11+ yrs     246
Name: count, dtype: int64

In [18]:
df_clean["IncomeQuartile"] = pd.qcut(
    df_clean["MonthlyIncome"], q=4,
    labels=["Q1 (lowest)", "Q2", "Q3", "Q4 (highest)"]
)
df_clean["IncomeQuartile"].value_counts()

IncomeQuartile
Q1 (lowest)     369
Q4 (highest)    368
Q3              367
Q2              366
Name: count, dtype: int64

In [19]:
print(df_clean.shape)
print(df_clean.isna().sum().sum())
df_clean.head()

(1470, 39)
0

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,YearsSinceLastPromotion,YearsWithCurrManager,Left,JobSatisfaction_label,Education_label,WorkLifeBalance_label,PerformanceRating_label,AgeGroup,TenureBand,IncomeQuartile
EmployeeNumber,,,,,,,,,,,,,,,,,,,,,
1,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,0,5,1,Very High,College,Bad,Excellent,36-45,6-10 yrs,Q3
2,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,1,7,0,Medium,Below College,Better,Outstanding,46-55,6-10 yrs,Q3
4,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,0,0,1,High,College,Better,Excellent,36-45,0-1 yrs,Q1 (lowest)
5,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,0,0,High,Master,Better,Excellent,26-35,6-10 yrs,Q1 (lowest)
7,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,2,2,0,Medium,Below College,Better,Excellent,26-35,2-3 yrs,Q2

In [22]:
df_clean.to_csv("ibm_attrition_clean.csv")

1. What is the shape of df_clean after Step 6, and how many columns did you add in Steps 3–5? df_clean.shape returns (1470, 39). Before it was (1470, 31), so I added 8 columns: Left; JobSatisfaction_label, Education_label, WorkLifeBalance_label and PerformanceRating_label; and AgeGroup, TenureBand and IncomeQuartile.


2. Which age group has the most employees? Which tenure band has the fewest? The age group that is large on numbers is 26 to 35 having 606 employees. Meanwhile, the fewest tenure band is 0 to 1 year.


3. Why did we keep the original JobSatisfaction numbers instead of replacing them with labels? The labels make tables and charts readable for HR leaders. The numbers keep the order in a form that statistics and models can use, since models need numeric inputs, not text. Keeping both means easy presenting of results clearly and analysis.


4. Using pd.qcut, each income quartile should have about 367 employees. Check whether that’s true, and if the counts differ slightly, why might that be? The quartiles have 369, 366, 367 and 368 employees, close to equal but not exact, for two reasons. Initially, 1,470 ÷ 4 = 367.5, and it's not feasible split an employee in half. Second, 121 employees share an exact income with someone else, and qcut must keep tied values in the same group, so the boundaries can’t land at perfectly equal counts.


5. Challenge: create a column called RecentlyPromoted that equals 1 if YearsSinceLastPromotion is 0 or 1, and 0 otherwise. 938 employees were promoted within the last year (value 1) and 532 were not (value 0). The mean is 0.638, so 63.8% of employees were recently promoted. As with Left, the average of a 0/1 column is the share of employees with the value 1.

# 3. Descriptive analytics

In [23]:
df_clean.groupby("Department")["Left"].mean()

Department
Human Resources           0.190476
Research & Development    0.138398
Sales                     0.206278
Name: Left, dtype: float64

In [24]:
dept = df_clean.groupby("Department").agg(
    employees=("Left", "size"),
    leavers=("Left", "sum"),
    attrition_rate=("Left", "mean"),
)
dept["share_of_leavers"] = dept["leavers"] / dept["leavers"].sum()
dept

                        employees  leavers  attrition_rate  share_of_leavers
Department
Human Resources                63       12        0.190476          0.050633
Research & Development        961      133        0.138398          0.561181
Sales                         446       92        0.206278          0.388186

In [25]:
company_rate = df_clean["Left"].mean()

def attrition_by(column):
    t = df_clean.groupby(column, observed=True).agg(
        employees=("Left", "size"),
        leavers=("Left", "sum"),
        attrition_rate=("Left", "mean"),
    )
    t["share_of_leavers"] = t["leavers"] / t["leavers"].sum()
    t["vs_company"] = t["attrition_rate"] / company_rate
    return t.sort_values("attrition_rate", ascending=False).round(3)

attrition_by("OverTime")

          employees  leavers  attrition_rate  share_of_leavers  vs_company
OverTime
Yes             416      127           0.305             0.536       1.894
No             1054      110           0.104             0.464       0.647

In [26]:
attrition_by("JobRole")
attrition_by("AgeGroup")
attrition_by("TenureBand")
attrition_by("IncomeQuartile")
attrition_by("MaritalStatus")
attrition_by("BusinessTravel")
attrition_by("JobSatisfaction_label")
attrition_by("Gender")

        employees  leavers  attrition_rate  share_of_leavers  vs_company
Gender
Male          882      150           0.170             0.633       1.055
Female        588       87           0.148             0.367       0.918

In [27]:
pd.crosstab(
    df_clean["JobRole"], df_clean["OverTime"],
    values=df_clean["Left"], aggfunc="mean"
).round(3)

OverTime                      No    Yes
JobRole
Healthcare Representative  0.074  0.054
Human Resources            0.179  0.385
Laboratory Technician      0.157  0.500
Manager                    0.013  0.148
Manufacturing Director     0.057  0.103
Research Director          0.018  0.043
Research Scientist         0.072  0.340
Sales Executive            0.112  0.330
Sales Representative       0.288  0.667

In [28]:
pd.crosstab(df_clean["JobRole"], df_clean["OverTime"])

OverTime                    No  Yes
JobRole
Healthcare Representative   94   37
Human Resources             39   13
Laboratory Technician      197   62
Manager                     75   27
Manufacturing Director     106   39
Research Director           57   23
Research Scientist         195   97
Sales Executive            232   94
Sales Representative        59   24

1. Which department has the highest attrition rate, and which has the most leavers? Explain in one sentence why they’re different.


2. Name the three job roles with the highest attrition rate. For each, give the rate, the vs_company value, and the number of employees.


3. Describe the pattern for TenureBand and IncomeQuartile. Does attrition rise or fall as tenure and income go up? Give the first and last group’s rates.


4. Look at JobSatisfaction_label. Is the pattern as clean as you’d expect? What surprises you?


5. From the overtime × job role crosstab, find the role where overtime makes the biggest difference (Yes rate minus No rate). Is that cell big enough to trust?


6. Leader summary: write 3 sentences for an HR director. Name the groups with the highest attrition risk, using numbers, and say where you’d look first.

#